server:
  port: 8080
  error:
    include:
      message: true

spring:
  application:
    name: rangiffler-gateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
  graphql:
    graphiql:
      enabled: true

rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'
rangiffler-users:
  base-uri: 'http://127.0.0.1:8089'

---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://rangiffler-auth:9000'

rangiffler-front:
  base-uri: 'http:/rangiffler-frontend:3001'
rangiffler-users:
  base-uri: 'http://rangiffler-users:8089'
---
