server:
  port: 8089
  error:
    include:
      message: true

spring:
  application:
    name: rangiffler-users
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: ${db.username}
    password: ${db.password}
    url: ${db.url}
  jpa:
    open-in-view: false
    database: default
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        check_nullability: true
        types.print.banner: false
        id.new_generator_mappings: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 500
          fetch_size: 1000
          lob.non_contextual_creation: true
        order_inserts: true
        order_updates: true
  flyway:
    baseline-on-migrate:
      true  enabled:
        true  locations:
          - classpath:db/migration
    url: ${db.url}
    user: ${db.username}
    password: ${db.password}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
db:
  url: 'jdbc:postgresql://localhost:5432/rangiffler-userdata'
  username: postgres
  password: secret
rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'
---
spring:
  config:
    activate:
      on-profile: 'docker'
db:
  url: 'jdbc:postgresql://rangiffler-all-db:5432/rangiffler-userdata'
  username: postgres
  password: secret
---